ALTER TABLE contact_inquiries
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(150),
    ADD COLUMN IF NOT EXISTS event_date VARCHAR(20),
    ADD COLUMN IF NOT EXISTS location VARCHAR(255),
    ADD COLUMN IF NOT EXISTS guest_count VARCHAR(50),
    ADD COLUMN IF NOT EXISTS budget_range VARCHAR(100),
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS source VARCHAR(50) DEFAULT 'contact_page';
